# -*- coding: utf-8 -*-
"""Desafio_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YPxZ9I238zS5lBjLOVquQz-dvl0oBcRj

# Desafio 1 - Carregar o dataframe e enviar para o Google  BigQuery

Importe as bibliotecas necessárias
Veririficar se existe dados nulos
Preencher dados se necessário
Conexão com o BigQuery
Enviar e gerar 3 insights
"""

#Importando as lib
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import datetime
from google.oauth2 import service_account
import gspread
import os
import sys

#alterando as configurações para exibir o máximo de colunas
pd.set_option('display.max_columns',None)

#ignorando os warnings
import warnings
warnings.filterwarnings('ignore')

#carregando o Data Frame de fornecedores
desafio1_fornecedores = pd.read_excel('FORNECEDORES.xlsx')

desafio1_fornecedores.head()

#verificando o DF Produtos
desafio1_Produtos.head(5)

"""# Carregando dados para o BigQuery"""

#Carregando as credenciais
credentials = service_account.Credentials.from_service_account_file(filename='datasciencegcs-a83f8f6ac567.json',
                                                                    scopes=["https://www.googleapis.com/auth/cloud-platform"])



#Enviando os dados
desafio1_fornecedores.to_gbq(credentials=credentials,
                             destination_table='DataSet_DataFaker.tblFornecedores',
                             if_exists='append')

