# -*- coding: utf-8 -*-
"""engenharia_reversa.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ENAk6B3g9uaCbrGveTX47qRcfrbKAPhW

# Procedimento Reverso -> Leitura no BQ
"""

import pandas as pd
from google.cloud import bigquery
from google.oauth2 import service_account

!pip install --upgrade pandas_gbq

"""# Leitura dos dados do BQ"""

query = '''
SELECT * FROM datasciencegcs.DataSet_DataFaker.Produtos
where cast(forn as numeric) = 2198
'''

"""# Credenciais"""

credentials = service_account.Credentials.from_service_account_file(filename="chave_bq/KEY_BQ.json",
                                                                   scopes=["https://www.googleapis.com/auth/cloud-platform"])

pd.read_gbq(credentials=credentials, query=query)







